import React from 'react'
import "./whatgta.css"
import Feature from '../../components/feature/feature'

const whatgta = () => {
    return (
        <div className='gpt3__whatgpt3 section-margin' id='wgpt3'>
           <div className='gpt3__whatgpt3-feature' >
            <Feature title="what is gpt-3" text="The quality of the text generated by GPT-3 is so high that it can be difficult to determine whether or not it was written by a human, which has both benefits and risks.May 28, 2020 paper introducing GPT-3. , an Australian philosopher, described GPT-3 as  of the most interesting and important AI systems ever" />
           </div>
           <div className='gpt3__whatgpt3-heading'>
               <h1 className='gradient-text'>the possibilities are beyond your imagine</h1>
               <p>Explore the library</p>
           </div>
           <div className='gpt3__whatgpt3-container'>
           <Feature title="chatbots" text="Generative Pre-trained Transformer  is an autoregressive  which has both benefits and risks. Thirty-one OpenAI researchers and engineers presented the original  paper introducing GPT-3. " />
           <Feature title="knowlege" text="Generative Pre-trained Transformer  is an autoregressive language model that uses deep learning to produce human-like text which has both benefits and risks. " />
           <Feature title="education" text="Generative Pre-trained Transformer  is an autoregressive language model that May 28, 2020 paper introducing GPT-3. , an Australian philosopher," />
           </div>
        </div>
    )
}

export default whatgta
