import React from 'react'
import "./possibility.css"
import Possibility from "../../assets/possibility.png"

const possibility = () => {
    return (
        <div className='gpt-possibility section-padding'>










        
            {/* <div className='gpt-possibility-image'>
                <img src={Possibility} />
            </div>
            <div className='gpt-possibility-content'>
                <h4>request early access to get started</h4>
                <h1 className='gradient-text'>the possibilities are beyond your imagine</h1>
                <p>
                    The quality of the text generated by GPT-3 is so high that it can be difficult to determine whether or not it was written by a human, which has both benefits and risks.May 28, 2020 paper introducing GPT-3. , an Australian philosopher, described GPT-3 as of the most interesting and important AI systems ever</p>
                    <h4>get started with open AI</h4>
            </div> */}
        </div>
    )
}

export default possibility
